export const strings = {
  en: {
    eyebrow:      "Together with their families",
    announcement: "joyfully announce their wedding",
    date:         "Saturday · 5 September 2026 · 4:00 PM",
    venue:        "Agriturismo da Pippo · Cassignanica, Italy",
    // countdown
    countdownLabel: "Days until we say “I do”",
    days:    "Days",
    hours:   "Hours",
    minutes: "Minutes",
    seconds: "Seconds",
    // nav
    home:     "Home",
    story:    "Our Story",
    details:  "Details",
    schedule: "Schedule",
    travel:   "Travel",
    registry: "Registry",
    rsvp:     "RSVP",
    // story
    storyTag:   "Our Story",
    storyTitle: "How It All Began",
    storyLead:  "It started with a chance meeting at a friend's dinner party in the autumn of 2021.",
    storyBody1: "James was telling a terrible joke about sourdough starters when Sarah laughed — not at the joke, but at the commitment it implied. That evening turned into a late-night walk along the South Bank, which turned into brunch the next morning, which turned into something neither of them expected.",
    storyBody2: "Four years, two adopted cats, and one spectacular sunset proposal on the Amalfi Coast later, they're ready to make it official — surrounded by the people who matter most.",
    // details
    detailsTag:    "The Details",
    detailsTitle:  "When & Where",
    ceremony:      "Ceremony",
    reception:     "Reception",
    dresscode:     "Dress Code",
    ceremonyTime:  "4:00 PM",
    receptionTime: "To follow",
    dresscodeType: "Semi-Formal",
    dresscodeNote: "Cocktail attire · Please avoid white or ivory",
    dinnerNote:    "Dinner, toasts & dancing",
    // schedule
    scheduleTag:   "The Day",
    scheduleTitle: "Schedule of Events",
    guestArrival:  "Guest Arrival",
    welcomeDrinks: "Welcome drinks on the terrace",
    exchangeVows:  "Exchange of vows",
    cocktailHour:  "Cocktail Hour",
    cocktailNote:  "Canapés & cocktails in the gardens",
    dinner:        "Dinner",
    dinnerSpeeches:"Dinner & speeches",
    firstDance:    "First Dance",
    partyBegins:   "The party begins",
    lastCall:      "Last Call & Send-Off",
    sendOff:       "Send-off under the stars",
    // travel
    travelTag:       "Getting There",
    travelTitle:     "Travel & Stay",
    accommodation:   "Accommodation",
    gettingThere:    "Getting There",
    thingsToDo:      "Things to Do",
    gettingThereNote:"Agriturismo da Pippo is located at Piazza Grassi 3, Cassignanica, easily reachable by car from Milan.",
    thingsToDoNote:  "Arriving early or staying late? We've put together a list of our favourite spots in the area.",
    viewMap:         "View on Map",
    ourPicks:        "Our Picks",
    // registry
    registryTag:    "Gifts",
    registryTitle:  "Registry",
    registryNote:   "Your presence is the greatest gift of all. However, if you wish to honour us with a gift, we've registered at the following:",
    giftRegistry:   "Gift Registry",
    honeymoonFund:  "Honeymoon Fund",
    // rsvp
    rsvpTag:        "Reply",
    rsvpDeadline:   "Kindly respond by 5 August 2026",
    fullName:       "Full Name",
    attending:      "Will you be attending?",
    joyfullyAccepts:"Joyfully Accepts",
    regretfullyDeclines: "Regretfully Declines",
    numberOfGuests: "Number of Guests",
    dietary:        "Dietary Requirements",
    songRequest:    "Song Request",
    sendRsvp:       "Send RSVP",
  },
  it: {
    eyebrow:      "Insieme alle loro famiglie",
    announcement: "annunciano con gioia il loro matrimonio",
    date:         "Sabato · 5 Settembre 2026 · ore 16:00",
    venue:        "Agriturismo da Pippo · Cassignanica, Italia",
    // countdown
    countdownLabel: "Giorni prima del “Sì, lo voglio”",
    days:    "Giorni",
    hours:   "Ore",
    minutes: "Minuti",
    seconds: "Secondi",
    // nav
    home:     "Home",
    story:    "La Nostra Storia",
    details:  "Dettagli",
    schedule: "Programma",
    travel:   "Come Arrivare",
    registry: "Lista Nozze",
    rsvp:     "RSVP",
    // story
    storyTag:   "La Nostra Storia",
    storyTitle: "Come Tutto è Iniziato",
    storyLead:  "Tutto è iniziato con un incontro casuale a una cena tra amici nell'autunno del 2021.",
    storyBody1: "James stava raccontando una battuta terribile sul lievito madre quando Sarah rise — non per la battuta, ma per la dedizione che implicava. Quella serata si trasformò in una passeggiata notturna lungo il South Bank, poi in un brunch la mattina dopo, e poi in qualcosa che nessuno dei due si aspettava.",
    storyBody2: "Quattro anni, due gatti adottati e una spettacolare proposta al tramonto sulla Costiera Amalfitana dopo, sono pronti a rendere tutto ufficiale — circondati dalle persone che contano di più.",
    // details
    detailsTag:    "I Dettagli",
    detailsTitle:  "Quando & Dove",
    ceremony:      "Cerimonia",
    reception:     "Ricevimento",
    dresscode:     "Dress Code",
    ceremonyTime:  "Ore 16:00",
    receptionTime: "A seguire",
    dresscodeType: "Elegante",
    dresscodeNote: "Cocktail attire · Si prega di evitare il bianco e l'avorio",
    dinnerNote:    "Cena, brindisi e festa",
    // schedule
    scheduleTag:   "La Giornata",
    scheduleTitle: "Programma",
    guestArrival:  "Arrivo Ospiti",
    welcomeDrinks: "Benvenuto con aperitivo",
    exchangeVows:  "Scambio delle promesse",
    cocktailHour:  "Aperitivo",
    cocktailNote:  "Cocktail e stuzzichini nel giardino",
    dinner:        "Cena",
    dinnerSpeeches:"Cena e discorsi",
    firstDance:    "Primo Ballo",
    partyBegins:   "Inizia la festa",
    lastCall:      "Chiusura",
    sendOff:       "Saluto finale sotto le stelle",
    // travel
    travelTag:       "Come Arrivare",
    travelTitle:     "Viaggio & Soggiorno",
    accommodation:   "Alloggio",
    gettingThere:    "Come Arrivare",
    thingsToDo:      "Cosa Fare",
    gettingThereNote:"L'Agriturismo da Pippo si trova a Piazza Grassi 3, Cassignanica, facilmente raggiungibile in auto da Milano.",
    thingsToDoNote:  "Arrivate presto o restate qualche giorno in più? Abbiamo raccolto i nostri posti preferiti della zona.",
    viewMap:         "Vedi Mappa",
    ourPicks:        "I Nostri Consigli",
    // registry
    registryTag:    "Regali",
    registryTitle:  "Lista Nozze",
    registryNote:   "La vostra presenza è il regalo più grande. Tuttavia, se desiderate onorarci con un dono, ecco i nostri suggerimenti:",
    giftRegistry:   "Lista Nozze",
    honeymoonFund:  "Luna di Miele",
    // rsvp
    rsvpTag:        "Rispondi",
    rsvpDeadline:   "Si richiede gentile conferma entro il 5 Agosto 2026",
    fullName:       "Nome e Cognome",
    attending:      "Parteciperai?",
    joyfullyAccepts:"Con gioia, accetto",
    regretfullyDeclines: "Purtroppo, declino",
    numberOfGuests: "Numero di Ospiti",
    dietary:        "Esigenze Alimentari",
    songRequest:    "Richiesta Musicale",
    sendRsvp:       "Invia RSVP",
  },
} as const;

export type Lang = keyof typeof strings;
export type StringKey = keyof typeof strings.en;
